import type { SignalType, ExpectedImpact, FieldSignal, LocationScope } from '../types/fieldSignal';

export const SIGNAL_TYPE_CONFIG: Record<
  SignalType,
  { label: string; iconName: string; description: string }
> = {
  local_event:          { label: 'Local Event',               iconName: 'Festival',        description: 'Festivals, fairs, markets, parades and other area-wide events' },
  major_sports_event:   { label: 'Major Sports Event',        iconName: 'SportsSoccer',     description: 'FIFA World Cup matches, Olympics, major tournaments, championship games' },
  entertainment_event:  { label: 'Entertainment / Concert',   iconName: 'MusicNote',        description: 'Concerts, world tours, stadium shows — e.g. Coldplay, Taylor Swift' },
  instore_event:        { label: 'In-Store Event',            iconName: 'Storefront',       description: 'Autograph signings, book launches, store promotions, product demos' },
  community_gathering:  { label: 'Community Gathering',       iconName: 'Groups',           description: 'Neighbourhood meetups, charity drives, religious gatherings, cultural events' },
  weather:              { label: 'Weather',                   iconName: 'Cloud',            description: 'Storms, heatwaves, floods, or other weather affecting foot traffic or delivery' },
  competitor_activity:  { label: 'Competitor Activity',       iconName: 'Store',            description: 'Competitor store openings, promotions, or price events near our location' },
  road_closure:         { label: 'Road Closure / Disruption', iconName: 'Traffic',          description: 'Roadwork, accidents, or closures that affect access or customer flow' },
  school_community_event:{ label: 'School / Academic Event',  iconName: 'School',           description: 'Graduations, back-to-school, prom, sports day — spikes in family demand' },
  staffing_impact:      { label: 'Staffing Impact',           iconName: 'PersonOff',        description: 'Sick calls, walkouts, or reduced staffing affecting operations' },
  other:                { label: 'Other',                     iconName: 'MoreHoriz',        description: 'Any other local signal not covered above' },
};

export const EXPECTED_IMPACT_CONFIG: Record<
  ExpectedImpact,
  { label: string; color: 'success' | 'warning' | 'error' | 'info' }
> = {
  demand_increase: { label: 'Demand Increase', color: 'success' },
  demand_drop: { label: 'Demand Drop', color: 'warning' },
  inventory_risk: { label: 'Inventory Risk', color: 'error' },
  staffing_impact: { label: 'Staffing Impact', color: 'warning' },
  operational_disruption: { label: 'Operational Disruption', color: 'error' },
  awareness_only: { label: 'Awareness Only', color: 'info' },
};

export const SIGNAL_STATUS_CONFIG: Record<
  'new' | 'reviewed' | 'closed',
  { label: string; color: 'warning' | 'info' | 'default' }
> = {
  new: { label: 'New', color: 'warning' },
  reviewed: { label: 'Reviewed', color: 'info' },
  closed: { label: 'Closed', color: 'default' },
};

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString();
const daysFromNow = (n: number) => new Date(now.getTime() + n * 86400000).toISOString().slice(0, 10);

export const MOCK_FIELD_SIGNALS: FieldSignal[] = [
  {
    id: 'FS-2401',
    signalType: 'local_event',
    title: 'Nashville Spring Fair — High Foot Traffic',
    description:
      'Annual spring fair at Centennial Park draws heavy weekend foot traffic. Expect increased beverage and snack demand Friday–Sunday. Parking on Main St will be limited.',
    locationScope: 'stores',
    storeId: '2341',
    storeName: 'Store #2341 — Nashville',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    department: 'Front End',
    impactStartDate: daysFromNow(2),
    impactEndDate: daysFromNow(5),
    expectedImpact: 'demand_increase',
    status: 'new',
    createdByUserId: 'u3',
    createdByName: 'Emily Parker',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    originalThreadId: 'c2',
    originalMessageId: 'fs-msg-1',
    activityLog: [
      {
        id: 'fsa-1',
        fieldSignalId: 'FS-2401',
        action: 'Field Signal created',
        actorUserId: 'u3',
        actorName: 'Emily Parker',
        timestamp: daysAgo(1),
      },
    ],
  },
  {
    id: 'FS-2402',
    signalType: 'weather',
    title: 'Severe Thunderstorm Watch — Delivery Delays',
    description:
      'National Weather Service issued severe thunderstorm watch through Thursday PM. Regional distribution center may delay morning deliveries by 4–6 hours.',
    storeId: '2034',
    storeName: 'Downtown Plaza #2034',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    impactStartDate: daysFromNow(0),
    impactEndDate: daysFromNow(2),
    expectedImpact: 'operational_disruption',
    status: 'reviewed',
    createdByUserId: 'user-003',
    createdByName: 'Marco Rossi',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0.5),
    reviewedByUserId: 'user-002',
    reviewedByName: 'John Doe',
    reviewedAt: daysAgo(0.5),
    originalThreadId: 'sm2',
    activityLog: [
      {
        id: 'fsa-2',
        fieldSignalId: 'FS-2402',
        action: 'Field Signal created',
        actorUserId: 'user-003',
        actorName: 'Marco Rossi',
        timestamp: daysAgo(2),
      },
      {
        id: 'fsa-3',
        fieldSignalId: 'FS-2402',
        action: 'Marked as Reviewed',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(0.5),
      },
    ],
  },
  {
    id: 'FS-2403',
    signalType: 'road_closure',
    title: 'I-40 East Lane Closure Near Store',
    description:
      'TDOT announced eastbound lane closure on I-40 exit 213 for bridge repair. Customer access via Highway 70 recommended; expect 20% traffic reduction.',
    storeId: '1142',
    storeName: 'Store #1142 — Memphis',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    impactStartDate: daysFromNow(-1),
    impactEndDate: daysFromNow(14),
    expectedImpact: 'demand_drop',
    status: 'new',
    createdByUserId: 'u6',
    createdByName: 'James Wilson',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    originalThreadId: 'c5',
    activityLog: [
      {
        id: 'fsa-4',
        fieldSignalId: 'FS-2403',
        action: 'Field Signal created',
        actorUserId: 'u6',
        actorName: 'James Wilson',
        timestamp: daysAgo(3),
      },
    ],
  },
  {
    id: 'FS-2404',
    signalType: 'competitor_activity',
    title: 'New Discount Grocery Opening 0.5 mi Away',
    description:
      'Competitor "ValueMart" grand opening Saturday with 15% off all categories first week. May pull price-sensitive shoppers from our location.',
    storeId: '2341',
    storeName: 'Store #2341 — Nashville',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    impactStartDate: daysFromNow(4),
    impactEndDate: daysFromNow(11),
    expectedImpact: 'demand_drop',
    status: 'closed',
    createdByUserId: 'u3',
    createdByName: 'Emily Parker',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
    reviewedByUserId: 'user-002',
    reviewedByName: 'John Doe',
    reviewedAt: daysAgo(5),
    closedByUserId: 'user-002',
    closedByName: 'John Doe',
    closedAt: daysAgo(1),
    linkedTaskId: 'tc-fs-2404',
    activityLog: [
      {
        id: 'fsa-5',
        fieldSignalId: 'FS-2404',
        action: 'Field Signal created',
        actorUserId: 'u3',
        actorName: 'Emily Parker',
        timestamp: daysAgo(7),
      },
      {
        id: 'fsa-6',
        fieldSignalId: 'FS-2404',
        action: 'Marked as Reviewed',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(5),
      },
      {
        id: 'fsa-7',
        fieldSignalId: 'FS-2404',
        action: 'Task created from signal',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(4),
        notes: 'Task #tc-fs-2404',
      },
      {
        id: 'fsa-8',
        fieldSignalId: 'FS-2404',
        action: 'Signal closed',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(1),
      },
    ],
  },
  {
    id: 'FS-2405',
    signalType: 'school_community_event',
    title: 'High School Graduation Week — Snack Spike',
    description:
      'Local high school graduation ceremonies all week. Families stocking up on party supplies, chips, and beverages. Peak days Wed–Sat.',
    storeId: '2034',
    storeName: 'Downtown Plaza #2034',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    impactStartDate: daysFromNow(1),
    impactEndDate: daysFromNow(6),
    expectedImpact: 'demand_increase',
    status: 'new',
    createdByUserId: 'user-003',
    createdByName: 'Marco Rossi',
    createdAt: daysAgo(0.3),
    updatedAt: daysAgo(0.3),
    originalThreadId: 'sm2',
    activityLog: [
      {
        id: 'fsa-9',
        fieldSignalId: 'FS-2405',
        action: 'Field Signal created',
        actorUserId: 'user-003',
        actorName: 'Marco Rossi',
        timestamp: daysAgo(0.3),
      },
    ],
  },
  {
    id: 'FS-2406',
    signalType: 'staffing_impact',
    title: 'Three Associates Out Sick — Morning Coverage Gap',
    description:
      'Three morning-shift associates called out. Reduced coverage on front end and dairy until replacements arrive ~2 PM.',
    storeId: '2034',
    storeName: 'Downtown Plaza #2034',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    impactStartDate: daysFromNow(0),
    impactEndDate: daysFromNow(0),
    expectedImpact: 'staffing_impact',
    status: 'reviewed',
    createdByUserId: 'user-003',
    createdByName: 'Marco Rossi',
    createdAt: daysAgo(0.1),
    updatedAt: daysAgo(0.05),
    reviewedByUserId: 'user-002',
    reviewedByName: 'John Doe',
    reviewedAt: daysAgo(0.05),
    originalThreadId: 'sm2',
    linkedBroadcastId: 'bc-fs-2406',
    activityLog: [
      {
        id: 'fsa-10',
        fieldSignalId: 'FS-2406',
        action: 'Field Signal created',
        actorUserId: 'user-003',
        actorName: 'Marco Rossi',
        timestamp: daysAgo(0.1),
      },
      {
        id: 'fsa-11',
        fieldSignalId: 'FS-2406',
        action: 'Marked as Reviewed',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(0.05),
      },
      {
        id: 'fsa-12',
        fieldSignalId: 'FS-2406',
        action: 'Broadcast created from signal',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(0.05),
        notes: 'Broadcast #bc-fs-2406',
      },
    ],
  },
  // ── New signal types: Major Sports, Entertainment, In-Store, Community ──
  {
    id: 'FS-2407',
    signalType: 'major_sports_event',
    title: 'FIFA World Cup Group Stage Matches — Venue Adjacent',
    description:
      'Store #2341 sits 0.8 mi from the stadium hosting three FIFA World Cup group stage matches (Jun 15, Jun 20, Jun 25). Combined attendance forecast: ~180,000 visitors across match days. Expect heavy pre-match foot traffic (−3h to kick-off), surge on branded apparel, fan accessories, and beverages. Post-match crowd dispersal may extend store trading hours by 2h.',
    locationScope: 'stores',
    storeId: '2341',
    storeName: 'Store #2341 — Nashville',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    department: 'Seasonal',
    impactStartDate: daysFromNow(8),
    impactEndDate: daysFromNow(21),
    expectedImpact: 'demand_increase',
    status: 'new',
    createdByUserId: 'u6',
    createdByName: 'James Wilson',
    createdAt: daysAgo(0.5),
    updatedAt: daysAgo(0.5),
    activityLog: [
      {
        id: 'fsa-13',
        fieldSignalId: 'FS-2407',
        action: 'Field Signal created',
        actorUserId: 'u6',
        actorName: 'James Wilson',
        timestamp: daysAgo(0.5),
      },
    ],
  },
  {
    id: 'FS-2408',
    signalType: 'entertainment_event',
    title: 'Coldplay Music of the Spheres World Tour — Nashville',
    description:
      'Coldplay performs two sold-out nights (50,000 capacity each) at Nissan Stadium, 1.2 mi from Downtown Plaza #2034. Demographic skews 18–35. Expect significant demand for casualwear, activewear, and accessories in the 48h window before each show. Previous tour data from similar markets showed 22–30% apparel sales uplift in adjacent stores.',
    locationScope: 'stores',
    storeId: '2034',
    storeName: 'Downtown Plaza #2034',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    department: 'Apparel',
    impactStartDate: daysFromNow(12),
    impactEndDate: daysFromNow(14),
    expectedImpact: 'demand_increase',
    status: 'new',
    createdByUserId: 'u3',
    createdByName: 'Emily Parker',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    originalThreadId: 'c-fs-pinned',
    originalMessageId: 'fspm-1',
    activityLog: [
      {
        id: 'fsa-14',
        fieldSignalId: 'FS-2408',
        action: 'Field Signal created',
        actorUserId: 'u3',
        actorName: 'Emily Parker',
        timestamp: daysAgo(1),
      },
    ],
  },
  {
    id: 'FS-2409',
    signalType: 'instore_event',
    title: 'Tennessee Titans — Player Autograph Signing In-Store',
    description:
      'Two Tennessee Titans wide receivers (confirmed) will host a 3-hour fan autograph session in our sporting goods aisle on Saturday 10 AM–1 PM. Coordinated with team PR; social media posts already live. Estimated 400–600 fans. Opportunities: fan apparel, accessories, exclusive merch drop. Recommend 3 additional floor staff and front-end support.',
    locationScope: 'stores',
    storeId: '2341',
    storeName: 'Store #2341 — Nashville',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    department: 'Seasonal',
    impactStartDate: daysFromNow(3),
    impactEndDate: daysFromNow(3),
    expectedImpact: 'demand_increase',
    status: 'reviewed',
    createdByUserId: 'u6',
    createdByName: 'James Wilson',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0.5),
    reviewedByUserId: 'user-002',
    reviewedByName: 'John Doe',
    reviewedAt: daysAgo(0.5),
    linkedTaskId: 'tc-fs-2409',
    originalThreadId: 'c-fs-pinned',
    originalMessageId: 'fspm-2',
    activityLog: [
      {
        id: 'fsa-15',
        fieldSignalId: 'FS-2409',
        action: 'Field Signal created',
        actorUserId: 'u6',
        actorName: 'James Wilson',
        timestamp: daysAgo(2),
      },
      {
        id: 'fsa-16',
        fieldSignalId: 'FS-2409',
        action: 'Marked as Reviewed',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(0.5),
      },
      {
        id: 'fsa-17',
        fieldSignalId: 'FS-2409',
        action: 'Task created from signal',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(0.5),
        notes: 'Task #tc-fs-2409 — staffing & merch prep',
      },
    ],
  },
  {
    id: 'FS-2410',
    signalType: 'instore_event',
    title: 'Book Launch — "The Retail Lens" Author Signing',
    description:
      'Bestselling author Priya Mehta will hold a signing session for her new book "The Retail Lens" in the Books & Stationery aisle, Saturday 2–5 PM. Event promoted by publisher on local radio. Expected 200–300 attendees, strong female 30–55 demographic. Book quantities pre-reserved; consider cross-merchandising journals, tote bags, and reading accessories.',
    locationScope: 'stores',
    storeId: '2034',
    storeName: 'Downtown Plaza #2034',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    department: 'Accessories',
    impactStartDate: daysFromNow(5),
    impactEndDate: daysFromNow(5),
    expectedImpact: 'demand_increase',
    status: 'new',
    createdByUserId: 'user-003',
    createdByName: 'Marco Rossi',
    createdAt: daysAgo(0.8),
    updatedAt: daysAgo(0.8),
    activityLog: [
      {
        id: 'fsa-18',
        fieldSignalId: 'FS-2410',
        action: 'Field Signal created',
        actorUserId: 'user-003',
        actorName: 'Marco Rossi',
        timestamp: daysAgo(0.8),
      },
    ],
  },
  {
    id: 'FS-2411',
    signalType: 'community_gathering',
    title: 'Riverside Community Fair — 3-Day Neighbourhood Event',
    description:
      'Annual Riverside Community Fair runs Friday–Sunday, three blocks from Store #3021 (Knoxville). ~8,000 attendees over the weekend. Vendor booths, food trucks, live music. Strong families and young-adult mix. Historically correlates with +15% traffic to our location and a spike in casual apparel, snacks, and reusable bags. Parking on Oak Ave unavailable Sat–Sun.',
    locationScope: 'stores',
    storeId: '3021',
    storeName: 'Store #3021 — Knoxville',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    department: 'Apparel',
    impactStartDate: daysFromNow(7),
    impactEndDate: daysFromNow(9),
    expectedImpact: 'demand_increase',
    status: 'new',
    createdByUserId: 'u5',
    createdByName: 'Lisa Thompson',
    createdAt: daysAgo(1.5),
    updatedAt: daysAgo(1.5),
    activityLog: [
      {
        id: 'fsa-19',
        fieldSignalId: 'FS-2411',
        action: 'Field Signal created',
        actorUserId: 'u5',
        actorName: 'Lisa Thompson',
        timestamp: daysAgo(1.5),
      },
    ],
  },
  {
    id: 'FS-2412',
    signalType: 'instore_event',
    title: 'Store-Hosted Back-to-School Promo Day',
    description:
      'Store-hosted promotional event: "Back-to-School Style Day" on Saturday — live DJ, student discount 15% off Kids and Accessories, photo station. Promoted via district social channels and school parent groups. Expected 500+ incremental visitors. POG for Kids section updated; ensure Kids Color Block Tee, Kids Cargo Shorts, and Canvas Tote are face-out and fully stocked. Incremental staffing approved.',
    locationScope: 'stores',
    storeId: '2034',
    storeName: 'Downtown Plaza #2034',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    department: 'Apparel',
    impactStartDate: daysFromNow(6),
    impactEndDate: daysFromNow(6),
    expectedImpact: 'demand_increase',
    status: 'reviewed',
    createdByUserId: 'user-003',
    createdByName: 'Marco Rossi',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    reviewedByUserId: 'user-002',
    reviewedByName: 'John Doe',
    reviewedAt: daysAgo(1),
    linkedBroadcastId: 'bc-fs-2412',
    activityLog: [
      {
        id: 'fsa-20',
        fieldSignalId: 'FS-2412',
        action: 'Field Signal created',
        actorUserId: 'user-003',
        actorName: 'Marco Rossi',
        timestamp: daysAgo(3),
      },
      {
        id: 'fsa-21',
        fieldSignalId: 'FS-2412',
        action: 'Marked as Reviewed',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(1),
      },
      {
        id: 'fsa-22',
        fieldSignalId: 'FS-2412',
        action: 'Broadcast created from signal',
        actorUserId: 'user-002',
        actorName: 'John Doe',
        timestamp: daysAgo(1),
        notes: 'Broadcast #bc-fs-2412 — district prep alert',
      },
    ],
  },
  {
    id: 'FS-2413',
    signalType: 'major_sports_event',
    title: 'SEC Championship Watch Parties — Multi-Store Impact',
    description:
      'SEC Championship game Saturday 3 PM. Multiple watch party venues within 1 mi of Stores #2341 and #2034. Local bars and community halls hosting ~2,000 fans collectively. Expect pre-game demand spike (Noon–3 PM) for snacks, casualwear, and fan accessories. Both stores should ensure adequate front-end staffing and Seasonal/Activewear floor presence.',
    locationScope: 'stores',
    affectedStoreIds: ['2341', '2034'],
    storeId: '2341',
    storeName: 'Store #2341 — Nashville',
    districtId: 'D14',
    districtName: 'District 14 — Tennessee',
    department: 'Seasonal',
    impactStartDate: daysFromNow(4),
    impactEndDate: daysFromNow(4),
    expectedImpact: 'demand_increase',
    status: 'new',
    createdByUserId: 'u3',
    createdByName: 'Emily Parker',
    createdAt: daysAgo(0.2),
    updatedAt: daysAgo(0.2),
    activityLog: [
      {
        id: 'fsa-23',
        fieldSignalId: 'FS-2413',
        action: 'Field Signal created',
        actorUserId: 'u3',
        actorName: 'Emily Parker',
        timestamp: daysAgo(0.2),
      },
    ],
  },
];

export const SIGNAL_TYPE_OPTIONS = (Object.keys(SIGNAL_TYPE_CONFIG) as SignalType[]).map(
  key => ({ value: key, label: SIGNAL_TYPE_CONFIG[key].label })
);

export const EXPECTED_IMPACT_OPTIONS = (Object.keys(EXPECTED_IMPACT_CONFIG) as ExpectedImpact[]).map(
  key => ({ value: key, label: EXPECTED_IMPACT_CONFIG[key].label })
);

/** Team members available for Field Signal notifications */
export const FIELD_SIGNAL_NOTIFY_CONTACTS: { id: string; name: string; role: string }[] = [
  { id: 'u1', name: 'Sarah Chen', role: 'District Manager' },
  { id: 'u2', name: 'Mike Rodriguez', role: 'Regional VP' },
  { id: 'u3', name: 'Emily Parker', role: 'Store Associate' },
  { id: 'u4', name: 'David Kim', role: 'Loss Prevention' },
  { id: 'u5', name: 'Lisa Thompson', role: 'Inventory Lead' },
  { id: 'u6', name: 'James Wilson', role: 'Store Manager' },
  { id: 'u7', name: 'Anna Martinez', role: 'POG Specialist' },
  { id: 'u8', name: 'Robert Chang', role: 'Operations Director' },
  { id: 'u9', name: 'Clarke T', role: 'Platform Administrator' },
];

export const FIELD_SIGNAL_NOTIFY_OPTIONS = FIELD_SIGNAL_NOTIFY_CONTACTS.map(c => ({
  value: c.id,
  label: `${c.name} · ${c.role}`,
}));

export const LOCATION_SCOPE_OPTIONS: { value: LocationScope; label: string; hint: string }[] = [
  { value: 'stores',   label: 'Store(s)',            hint: 'Select one or more specific stores' },
  { value: 'zip_code', label: 'ZIP Code / Local Area', hint: 'Signal is tied to a ZIP code or local neighborhood' },
  { value: 'city',     label: 'City',                hint: 'Signal applies across an entire city' },
  { value: 'state',    label: 'State',               hint: 'Signal applies across an entire state' },
];

export const DEPARTMENT_OPTIONS = [
  { value: '',            label: 'All Departments',           group: '' },
  // Apparel departments — mirrors Planogram Intelligence and product catalog
  { value: "Women's",     label: "Women's",                   group: 'Apparel' },
  { value: "Men's",       label: "Men's",                     group: 'Apparel' },
  { value: 'Kids',        label: 'Kids',                      group: 'Apparel' },
  { value: 'Accessories', label: 'Accessories',               group: 'Apparel' },
  { value: 'Footwear',    label: 'Footwear',                  group: 'Apparel' },
  { value: 'Activewear',  label: 'Activewear',                group: 'Apparel' },
  { value: 'Seasonal',    label: 'Seasonal / Outerwear',      group: 'Apparel' },
  { value: 'Denim',       label: 'Denim (Cross-dept)',        group: 'Apparel' },
  // Store operations
  { value: 'FrontEnd',    label: 'Front End / Checkout',      group: 'Store Operations' },
  { value: 'Backroom',    label: 'Backroom / Receiving',      group: 'Store Operations' },
  { value: 'Loss',        label: 'Loss Prevention',           group: 'Store Operations' },
  { value: 'Fitting',     label: 'Fitting Rooms',             group: 'Store Operations' },
  { value: 'Visual',      label: 'Visual Merchandising',      group: 'Store Operations' },
  { value: 'Stockroom',   label: 'Stockroom / Inventory',     group: 'Store Operations' },
];

/** Mock store list for dropdowns */
export const STORE_OPTIONS = [
  { value: '2341', label: 'Store #2341 — Nashville, TN',    district: 'D14', zip: '37201', state: 'Tennessee' },
  { value: '1142', label: 'Store #1142 — Memphis, TN',      district: 'D14', zip: '38103', state: 'Tennessee' },
  { value: '2034', label: 'Downtown Plaza #2034 — Nashville, TN', district: 'D14', zip: '37219', state: 'Tennessee' },
  { value: '3021', label: 'Store #3021 — Knoxville, TN',   district: 'D14', zip: '37902', state: 'Tennessee' },
  { value: '4112', label: 'Store #4112 — Chattanooga, TN', district: 'D15', zip: '37402', state: 'Tennessee' },
  { value: '4523', label: 'Store #4523 — Murfreesboro, TN',district: 'D15', zip: '37130', state: 'Tennessee' },
  { value: '5001', label: 'Store #5001 — Atlanta, GA',      district: 'D22', zip: '30301', state: 'Georgia' },
  { value: '5219', label: 'Store #5219 — Alpharetta, GA',   district: 'D22', zip: '30004', state: 'Georgia' },
];

/** Mock district list for dropdowns */
export const DISTRICT_OPTIONS = [
  { value: 'D14', label: 'District 14 — Tennessee (Central)', state: 'Tennessee' },
  { value: 'D15', label: 'District 15 — Tennessee (East)',    state: 'Tennessee' },
  { value: 'D22', label: 'District 22 — Georgia',            state: 'Georgia' },
  { value: 'D31', label: 'District 31 — Alabama',            state: 'Alabama' },
  { value: 'D40', label: 'District 40 — Kentucky',           state: 'Kentucky' },
];

export const US_STATES = [
  'Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut',
  'Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa',
  'Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan',
  'Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire',
  'New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio',
  'Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota',
  'Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia',
  'Wisconsin','Wyoming',
].map(s => ({ value: s, label: s }));
