import type {
  StoreMeta,
  ProductOpportunity,
  AllocationRequest,
  ExecutionRecord,
  OpportunityStatus,
} from '../types/productOpportunity';

export const STORES: StoreMeta[] = [
  { storeId: 'STR-001', storeName: 'Downtown Flagship', region: 'Northeast', cluster: 'Metro-A', allocationCycle: 'Q2-2026-W21', lastRefreshed: '2026-05-21T14:30:00Z' },
  { storeId: 'STR-002', storeName: 'Suburban Mall East', region: 'Southeast', cluster: 'Suburban-B', allocationCycle: 'Q2-2026-W21', lastRefreshed: '2026-05-21T14:30:00Z' },
  { storeId: 'STR-003', storeName: 'Harbor Point', region: 'West', cluster: 'Coastal-C', allocationCycle: 'Q2-2026-W21', lastRefreshed: '2026-05-21T14:30:00Z' },
  { storeId: 'STR-004', storeName: 'Midtown Express', region: 'Northeast', cluster: 'Metro-A', allocationCycle: 'Q2-2026-W21', lastRefreshed: '2026-05-20T09:15:00Z' },
];

export const DEFAULT_STORE_ID = 'STR-001';

// SKU-keyed product images — matched to actual product category and name
const SKU_IMAGES: Record<string, string> = {
  'WOM-BLZ-001': 'https://images.unsplash.com/photo-1629726343583-d9718b3e8f3f?w=120&h=120&fit=crop', // Women's Classic Blazer
  'WOM-TOP-014': 'https://images.unsplash.com/photo-1624484631620-9e53e4aed980?w=120&h=120&fit=crop', // Women's V-Neck Basics
  'WOM-DRS-014': 'https://images.unsplash.com/photo-1777888784810-3a42d674d97b?w=120&h=120&fit=crop', // Floral Midi Dress — Navy
  'WOM-DNM-005': 'https://images.unsplash.com/photo-1714143164072-7646ef5cb24d?w=120&h=120&fit=crop', // High-Rise Skinny Jeans
  'WOM-OUT-003': 'https://images.unsplash.com/photo-1724709972210-4beb408de580?w=120&h=120&fit=crop', // Wool Trench Coat
  'WOM-ACT-002': 'https://images.unsplash.com/photo-1762331655528-4af4bccf7c62?w=120&h=120&fit=crop', // Athletic Leggings
  'MEN-PLO-002': 'https://images.unsplash.com/photo-1720514496503-c399e2af61d2?w=120&h=120&fit=crop', // Men's Polo Classic
  'MEN-DNM-003': 'https://images.unsplash.com/photo-1714143164072-7646ef5cb24d?w=120&h=120&fit=crop', // Slim Fit Denim — Dark Wash
  'MEN-OUT-006': 'https://images.unsplash.com/photo-1769467701268-6a24ece1d417?w=120&h=120&fit=crop', // Puffer Jacket
  'MEN-ACT-004': 'https://images.unsplash.com/photo-1613593013133-b6e122feafe8?w=120&h=120&fit=crop', // Athletic Compression Tee
  'MEN-CHN-007': 'https://images.unsplash.com/photo-1624378439575-d8705ad01f20?w=120&h=120&fit=crop', // Men's Stretch Chino
  'KID-SHT-019': 'https://images.unsplash.com/photo-1632337950445-ba446cb0e26f?w=120&h=120&fit=crop', // Kids Cargo Shorts
  'ACC-BAG-005': 'https://images.unsplash.com/photo-1572966059657-6e8910c8c3c0?w=120&h=120&fit=crop', // Canvas Tote Bag
  'ACC-BAG-011': 'https://images.unsplash.com/photo-1569484221992-2a453658fff3?w=120&h=120&fit=crop', // Leather Crossbody Bag
  'ACC-SCF-009': 'https://images.unsplash.com/photo-1635417198137-75d31b8045e2?w=120&h=120&fit=crop', // Silk Blend Scarf
  'ACC-BLT-011': 'https://images.unsplash.com/photo-1596159981047-a1eabbc2595b?w=120&h=120&fit=crop', // Leather Belt Classic
  'FTW-RUN-002': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&h=120&fit=crop',   // Running Shoes Elite
  'SEA-HOO-014': 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=120&h=120&fit=crop',   // Limited Edition Hoodie
  'SEA-JKT-004': 'https://images.unsplash.com/photo-1559433101-fd3dfc8823ae?w=120&h=120&fit=crop',   // Seasonal Rain Jacket
};
const DEFAULT_PRODUCT_IMAGE = 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=120&h=120&fit=crop';

const makeOpp = (
  idx: number,
  storeId: string,
  overrides: Partial<ProductOpportunity>,
): ProductOpportunity => {
  const base: ProductOpportunity = {
    id: `OPP-${String(idx).padStart(4, '0')}`,
    storeId,
    storeName: STORES.find(s => s.storeId === storeId)?.storeName ?? '',
    region: STORES.find(s => s.storeId === storeId)?.region ?? '',
    productImage: overrides.sku ? (SKU_IMAGES[overrides.sku] ?? DEFAULT_PRODUCT_IMAGE) : DEFAULT_PRODUCT_IMAGE,
    productName: `Product ${idx}`,
    sku: `SKU-${String(10000 + idx)}`,
    category: 'General',
    opportunityType: 'top_performing',
    opportunityValue: 2500,
    hoAllocationId: `HO-ALQ-${String(idx).padStart(4, '0')}`,
    allocationCycle: 'Q2-2026-W21',
    allocationDate: '2026-05-10',
    allocatorName: 'Sarah Mitchell',
    allocationReleaseDate: '2026-05-12',
    currentHoAllocationQty: 100,
    receivedQty: 60,
    inTransitQty: 20,
    pendingAllocationQty: 0,
    allocationStatus: 'Active',
    allocationVersion: 1,
    allocationReason: 'Standard Replenishment',
    recommendedAllocationQty: 140,
    allocationGap: 40,
    currentStoreStock: 35,
    requiredQty: 140,
    dcAvailableQty: 500,
    transferAvailableQty: 80,
    salesLast7Days: 42,
    salesLast30Days: 165,
    sellThroughPct: 78,
    forecastDemand: 180,
    safetyStock: 25,
    stockoutRisk: 'medium',
    comparableStorePerformance: '+12% vs cluster avg',
    status: 'open',
    currentOwner: 'Store Team',
    currentStage: 'Review',
    lastUpdated: '2026-05-21T10:00:00Z',
    flagReason: 'This product is flagged because sales velocity is higher than forecast and the current allocation may not be sufficient to meet demand.',
    suggestedAction: 'Request additional allocation from DC',
    recommendedFulfillmentPath: 'dc_allocation',
    lostSalesRisk: 1800,
    expectedCoverageImprovement: '+15 days coverage',
    priority: 'high',
  };
  return { ...base, ...overrides };
};

export const MOCK_OPPORTUNITIES: ProductOpportunity[] = [
  makeOpp(1, 'STR-001', {
    productName: "Women's Classic Blazer",
    sku: 'WOM-BLZ-001',
    category: 'Apparel',
    opportunityType: 'top_performing',
    opportunityValue: 4200,
    currentHoAllocationQty: 80,
    recommendedAllocationQty: 140,
    allocationGap: 60,
    currentStoreStock: 18,
    salesLast7Days: 56,
    salesLast30Days: 210,
    sellThroughPct: 85,
    forecastDemand: 220,
    dcAvailableQty: 600,
    transferAvailableQty: 45,
    status: 'open',
    priority: 'critical',
    stockoutRisk: 'high',
    flagReason: 'This product is flagged because sales velocity is 35% higher than forecast and current stock will be depleted within 2 days at current sell-through rate.',
    lostSalesRisk: 3500,
  }),
  makeOpp(2, 'STR-001', {
    productName: "Women's V-Neck Basics",
    sku: 'WOM-TOP-014',
    category: 'Apparel',
    opportunityType: 'top_performing',
    opportunityValue: 3100,
    currentHoAllocationQty: 120,
    recommendedAllocationQty: 180,
    allocationGap: 60,
    currentStoreStock: 42,
    salesLast7Days: 38,
    salesLast30Days: 155,
    forecastDemand: 175,
    status: 'in_progress',
    currentOwner: 'James Park',
    currentStage: 'Editing Allocation',
    priority: 'high',
    flagReason: 'This product is flagged because it is consistently the #1 seller in its category and current allocation leaves a gap of 60 units vs demand.',
  }),
  makeOpp(3, 'STR-001', {
    productName: 'Floral Midi Dress — Navy',
    sku: 'WOM-DRS-014',
    category: 'Apparel',
    opportunityType: 'emerging',
    opportunityValue: 1850,
    currentHoAllocationQty: 50,
    recommendedAllocationQty: 90,
    allocationGap: 40,
    currentStoreStock: 12,
    salesLast7Days: 28,
    salesLast30Days: 95,
    sellThroughPct: 72,
    forecastDemand: 110,
    dcAvailableQty: 300,
    transferAvailableQty: 60,
    status: 'pending_approval',
    currentOwner: 'Approval Queue',
    currentStage: 'Awaiting Approval',
    priority: 'medium',
    flagReason: "This product is flagged as emerging because recent sell-through is trending 22% above comparable stores in the cluster.",
    suggestedAction: 'Request additional allocation from DC',
    stockoutRisk: 'medium',
  }),
  makeOpp(4, 'STR-001', {
    productName: 'Puffer Jacket',
    sku: 'MEN-OUT-006',
    category: 'Apparel',
    opportunityType: 'top_performing',
    opportunityValue: 5500,
    currentHoAllocationQty: 40,
    recommendedAllocationQty: 65,
    allocationGap: 25,
    currentStoreStock: 8,
    salesLast7Days: 15,
    salesLast30Days: 58,
    dcAvailableQty: 200,
    transferAvailableQty: 30,
    status: 'approved',
    currentOwner: 'Execution Team',
    currentStage: 'Ready for Execution',
    priority: 'high',
    stockoutRisk: 'high',
    flagReason: 'This product is flagged because current inventory is below safety stock and replenishment is urgently required.',
  }),
  makeOpp(5, 'STR-001', {
    productName: 'Athletic Leggings',
    sku: 'WOM-ACT-002',
    category: 'Apparel',
    opportunityType: 'emerging',
    opportunityValue: 980,
    currentHoAllocationQty: 60,
    recommendedAllocationQty: 85,
    allocationGap: 25,
    currentStoreStock: 22,
    salesLast7Days: 18,
    salesLast30Days: 72,
    dcAvailableQty: 400,
    transferAvailableQty: 55,
    status: 'actioned',
    currentOwner: 'DC Operations',
    currentStage: 'Executing',
    priority: 'medium',
    flagReason: 'This product is flagged as emerging because recent sell-through is trending above comparable stores.',
  }),
  makeOpp(6, 'STR-001', {
    productName: 'Kids Cargo Shorts',
    sku: 'KID-SHT-019',
    category: 'Apparel',
    opportunityType: 'at_risk',
    opportunityValue: 1200,
    currentHoAllocationQty: 30,
    recommendedAllocationQty: 50,
    allocationGap: 20,
    currentStoreStock: 5,
    salesLast7Days: 12,
    salesLast30Days: 48,
    dcAvailableQty: 10,
    transferAvailableQty: 35,
    status: 'closed',
    currentOwner: 'Completed',
    currentStage: 'Closed',
    priority: 'low',
    stockoutRisk: 'low',
    flagReason: 'This product was flagged as at-risk due to low stock. Allocation has been fulfilled and confirmed.',
    recommendedFulfillmentPath: 'combined',
    suggestedAction: 'Request partial DC allocation + store-to-store transfer',
  }),
  makeOpp(7, 'STR-001', {
    productName: 'Leather Crossbody Bag',
    sku: 'ACC-BAG-011',
    category: 'Accessories',
    opportunityType: 'at_risk',
    opportunityValue: 3800,
    currentHoAllocationQty: 25,
    recommendedAllocationQty: 45,
    allocationGap: 20,
    currentStoreStock: 3,
    salesLast7Days: 9,
    salesLast30Days: 35,
    dcAvailableQty: 0,
    transferAvailableQty: 15,
    status: 'rejected',
    currentOwner: 'Sarah Mitchell',
    currentStage: 'Rejected',
    priority: 'medium',
    stockoutRisk: 'high',
    flagReason: 'This product is flagged as at-risk because current inventory is below safety stock and replenishment is required.',
    recommendedFulfillmentPath: 'store_transfer',
    suggestedAction: 'Request store-to-store transfer',
  }),
  makeOpp(8, 'STR-001', {
    productName: 'Canvas Tote Bag',
    sku: 'ACC-BAG-005',
    category: 'Accessories',
    opportunityType: 'top_performing',
    opportunityValue: 2900,
    currentHoAllocationQty: 45,
    recommendedAllocationQty: 70,
    allocationGap: 25,
    currentStoreStock: 10,
    salesLast7Days: 22,
    salesLast30Days: 88,
    dcAvailableQty: 350,
    transferAvailableQty: 40,
    status: 'unresolved',
    currentOwner: 'Unresolved',
    currentStage: 'SLA Missed',
    priority: 'critical',
    stockoutRisk: 'high',
    flagReason: 'This product is flagged because approval has been pending beyond the SLA deadline and requires immediate attention.',
  }),
  makeOpp(9, 'STR-001', {
    productName: 'Silk Blend Scarf',
    sku: 'ACC-SCF-009',
    category: 'Accessories',
    opportunityType: 'emerging',
    opportunityValue: 1650,
    currentHoAllocationQty: 35,
    recommendedAllocationQty: 55,
    allocationGap: 20,
    currentStoreStock: 15,
    salesLast7Days: 14,
    salesLast30Days: 52,
    dcAvailableQty: 250,
    status: 'open',
    priority: 'medium',
    flagReason: 'This product is flagged as emerging because recent sell-through is trending above comparable stores in the cluster.',
  }),
  makeOpp(10, 'STR-001', {
    productName: 'Wool Trench Coat',
    sku: 'WOM-OUT-003',
    category: 'Apparel',
    opportunityType: 'at_risk',
    opportunityValue: 750,
    currentHoAllocationQty: 20,
    recommendedAllocationQty: 35,
    allocationGap: 15,
    currentStoreStock: 4,
    salesLast7Days: 8,
    salesLast30Days: 30,
    dcAvailableQty: 0,
    transferAvailableQty: 0,
    status: 'open',
    priority: 'high',
    stockoutRisk: 'high',
    flagReason: 'This product is flagged as at-risk because current inventory is critically low with no DC or transfer availability.',
    recommendedFulfillmentPath: 'escalate',
    suggestedAction: 'Escalate to allocator',
  }),
  makeOpp(11, 'STR-001', {
    productName: 'Running Shoes Elite',
    sku: 'FTW-RUN-002',
    category: 'Footwear',
    opportunityType: 'top_performing',
    opportunityValue: 6200,
    currentHoAllocationQty: 60,
    recommendedAllocationQty: 95,
    allocationGap: 35,
    currentStoreStock: 14,
    salesLast7Days: 32,
    salesLast30Days: 128,
    dcAvailableQty: 450,
    status: 'in_progress',
    currentOwner: 'Anna Chen',
    currentStage: 'Draft Saved',
    priority: 'critical',
    flagReason: 'This product is the #1 revenue driver in footwear with a significant allocation gap of 35 units.',
  }),
  makeOpp(12, 'STR-001', {
    productName: 'Limited Edition Hoodie',
    sku: 'SEA-HOO-014',
    category: 'Seasonal',
    opportunityType: 'emerging',
    opportunityValue: 890,
    currentHoAllocationQty: 25,
    recommendedAllocationQty: 40,
    allocationGap: 15,
    currentStoreStock: 9,
    salesLast7Days: 10,
    salesLast30Days: 38,
    dcAvailableQty: 180,
    status: 'pending_approval',
    currentOwner: 'Approval Queue',
    currentStage: 'Awaiting Approval',
    priority: 'low',
    flagReason: 'This product is flagged as emerging with consistent week-over-week growth in the home category.',
  }),
];

export const MOCK_ALLOCATION_REQUESTS: AllocationRequest[] = [
  {
    requestId: 'REQ-0001',
    opportunityId: 'OPP-0003',
    storeId: 'STR-001',
    storeName: 'Downtown Flagship',
    region: 'Northeast',
    productImage: SKU_IMAGES['WOM-DRS-014'],
    productName: 'Floral Midi Dress — Navy',
    sku: 'WOM-DRS-014',
    category: 'Apparel',
    opportunityType: 'emerging',
    opportunityValue: 1850,
    currentHoAllocationQty: 50,
    recommendedAllocationQty: 90,
    editedAllocationQty: 85,
    approvedAllocationQty: 0,
    fulfillmentSource: 'dc_allocation',
    requiredByDate: '2026-05-28',
    reasonCode: 'emerging_trend',
    comment: "Strong emerging trend in Women's Dresses — requesting increased allocation to match rising demand.",
    diffVsRecommendation: -5,
    allocationDelta: 35,
    submittedBy: 'James Park',
    submittedDate: '2026-05-19T14:30:00Z',
    slaDueDate: '2026-05-23T23:59:00Z',
    status: 'pending_approval',
    dcAvailableQty: 300,
    transferAvailableQty: 60,
    salesLast7Days: 28,
    salesLast30Days: 95,
    forecastDemand: 110,
    currentStoreStock: 12,
    inTransitQty: 20,
    receivedQty: 60,
  },
  {
    requestId: 'REQ-0002',
    opportunityId: 'OPP-0012',
    storeId: 'STR-001',
    storeName: 'Downtown Flagship',
    region: 'Northeast',
    productImage: SKU_IMAGES['SEA-HOO-014'],
    productName: 'Limited Edition Hoodie',
    sku: 'SEA-HOO-014',
    category: 'Seasonal',
    opportunityType: 'emerging',
    opportunityValue: 890,
    currentHoAllocationQty: 25,
    recommendedAllocationQty: 40,
    editedAllocationQty: 40,
    approvedAllocationQty: 0,
    fulfillmentSource: 'dc_allocation',
    requiredByDate: '2026-05-30',
    reasonCode: 'emerging_trend',
    comment: '',
    diffVsRecommendation: 0,
    allocationDelta: 15,
    submittedBy: 'Anna Chen',
    submittedDate: '2026-05-20T09:15:00Z',
    slaDueDate: '2026-05-24T23:59:00Z',
    status: 'pending_approval',
    dcAvailableQty: 180,
    transferAvailableQty: 25,
    salesLast7Days: 10,
    salesLast30Days: 38,
    forecastDemand: 50,
    currentStoreStock: 9,
    inTransitQty: 10,
    receivedQty: 25,
  },
  {
    requestId: 'REQ-0003',
    opportunityId: 'OPP-0004',
    storeId: 'STR-001',
    storeName: 'Downtown Flagship',
    region: 'Northeast',
    productImage: SKU_IMAGES['MEN-PLO-002'],
    productName: "Men's Polo Classic",
    sku: 'MEN-PLO-002',
    category: 'Apparel',
    opportunityType: 'top_performing',
    opportunityValue: 5500,
    currentHoAllocationQty: 40,
    recommendedAllocationQty: 65,
    editedAllocationQty: 60,
    approvedAllocationQty: 60,
    fulfillmentSource: 'dc_allocation',
    requiredByDate: '2026-05-25',
    reasonCode: 'high_velocity',
    comment: 'Critical stock item — high velocity sales requiring immediate replenishment.',
    diffVsRecommendation: -5,
    allocationDelta: 20,
    submittedBy: 'James Park',
    submittedDate: '2026-05-17T11:00:00Z',
    slaDueDate: '2026-05-21T23:59:00Z',
    status: 'approved',
    approver: 'Sarah Mitchell',
    approvalDate: '2026-05-18T16:00:00Z',
    dcAvailableQty: 200,
    transferAvailableQty: 30,
    salesLast7Days: 15,
    salesLast30Days: 58,
    forecastDemand: 70,
    currentStoreStock: 8,
    inTransitQty: 15,
    receivedQty: 40,
  },
];

export const MOCK_EXECUTION_RECORDS: ExecutionRecord[] = [
  {
    executionId: 'EXC-0001',
    requestId: 'REQ-0003',
    storeId: 'STR-001',
    storeName: 'Downtown Flagship',
    productImage: SKU_IMAGES['MEN-PLO-002'],
    productName: "Men's Polo Classic",
    sku: 'MEN-PLO-002',
    fulfillmentPath: 'dc_allocation',
    approvedAllocationQty: 60,
    executionStatus: 'approved',
    downstreamSystemStatus: 'Pending WMS',
    sentToExecutionDate: '',
    executionConfirmationDate: '',
    currentOwner: 'DC Operations',
    currentStage: 'Awaiting Dispatch',
    slaDueDate: '2026-05-25T23:59:00Z',
    status: 'approved',
  },
  {
    executionId: 'EXC-0002',
    requestId: 'REQ-0005',
    storeId: 'STR-001',
    storeName: 'Downtown Flagship',
    productImage: SKU_IMAGES['WOM-DNM-005'],
    productName: 'High-Rise Skinny Jeans',
    sku: 'WOM-DNM-005',
    fulfillmentPath: 'dc_allocation',
    approvedAllocationQty: 85,
    executionStatus: 'actioned',
    downstreamSystemStatus: 'Dispatched — In Transit',
    sentToExecutionDate: '2026-05-19T08:00:00Z',
    executionConfirmationDate: '',
    currentOwner: 'Logistics',
    currentStage: 'In Transit',
    slaDueDate: '2026-05-24T23:59:00Z',
    status: 'actioned',
  },
  {
    executionId: 'EXC-0003',
    requestId: 'REQ-0006',
    storeId: 'STR-001',
    storeName: 'Downtown Flagship',
    productImage: SKU_IMAGES['MEN-CHN-007'],
    productName: "Men's Stretch Chino",
    sku: 'MEN-CHN-007',
    fulfillmentPath: 'combined',
    approvedAllocationQty: 50,
    executionStatus: 'closed',
    downstreamSystemStatus: 'Delivered & Confirmed',
    sentToExecutionDate: '2026-05-15T09:00:00Z',
    executionConfirmationDate: '2026-05-18T14:30:00Z',
    currentOwner: 'Completed',
    currentStage: 'Closed',
    slaDueDate: '2026-05-20T23:59:00Z',
    status: 'closed',
  },
  {
    executionId: 'EXC-0004',
    requestId: 'REQ-0007',
    storeId: 'STR-001',
    storeName: 'Downtown Flagship',
    productImage: SKU_IMAGES['ACC-BLT-011'],
    productName: 'Leather Belt Classic',
    sku: 'ACC-BLT-011',
    fulfillmentPath: 'store_transfer',
    approvedAllocationQty: 0,
    executionStatus: 'rejected',
    downstreamSystemStatus: 'N/A',
    sentToExecutionDate: '',
    executionConfirmationDate: '',
    currentOwner: 'N/A',
    currentStage: 'Rejected',
    slaDueDate: '2026-05-22T23:59:00Z',
    status: 'rejected',
  },
  {
    executionId: 'EXC-0005',
    requestId: 'REQ-0008',
    storeId: 'STR-001',
    storeName: 'Downtown Flagship',
    productImage: SKU_IMAGES['ACC-BAG-011'],
    productName: 'Leather Crossbody Bag',
    sku: 'ACC-BAG-011',
    fulfillmentPath: 'dc_allocation',
    approvedAllocationQty: 70,
    executionStatus: 'unresolved',
    downstreamSystemStatus: 'Confirmation Pending — SLA Exceeded',
    sentToExecutionDate: '2026-05-14T10:00:00Z',
    executionConfirmationDate: '',
    currentOwner: 'Unresolved',
    currentStage: 'SLA Missed',
    slaDueDate: '2026-05-19T23:59:00Z',
    status: 'unresolved',
  },
];

export function getOpportunitiesByStore(storeId: string): ProductOpportunity[] {
  return MOCK_OPPORTUNITIES.filter(o => o.storeId === storeId);
}

export function getOpportunityById(id: string): ProductOpportunity | undefined {
  return MOCK_OPPORTUNITIES.find(o => o.id === id);
}

/* ── Runtime approval queue (persists across navigations within the session) ── */
const _runtimeRequests: AllocationRequest[] = [];
let _reqCounter = MOCK_ALLOCATION_REQUESTS.length + 1;

export function addApprovalRequest(req: Omit<AllocationRequest, 'requestId' | 'status' | 'submittedDate' | 'slaDueDate'>): void {
  const now = new Date();
  const sla = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000); // 3-day SLA
  _runtimeRequests.unshift({
    ...req,
    requestId: `REQ-${String(_reqCounter++).padStart(4, '0')}`,
    status: 'pending_approval',
    submittedDate: now.toISOString(),
    slaDueDate: sla.toISOString(),
  } as AllocationRequest);
}

export function getApprovalRequests(): AllocationRequest[] {
  const base = MOCK_ALLOCATION_REQUESTS.filter(r => r.status === 'pending_approval');
  return [..._runtimeRequests, ...base];
}

export function getExecutionRecords(): ExecutionRecord[] {
  return MOCK_EXECUTION_RECORDS;
}

export function getOpportunitySummary(opportunities: ProductOpportunity[]) {
  const byStatus = (s: OpportunityStatus) => opportunities.filter(o => o.status === s).length;
  const totalValue = opportunities.reduce((sum, o) => sum + o.opportunityValue, 0);
  return {
    totalOpen: byStatus('open'),
    inProgress: byStatus('in_progress'),
    pendingApproval: byStatus('pending_approval'),
    approved: byStatus('approved'),
    actioned: byStatus('actioned'),
    closed: byStatus('closed'),
    rejected: byStatus('rejected'),
    unresolved: byStatus('unresolved'),
    totalValue,
  };
}

export function getStoreById(id: string): StoreMeta | undefined {
  return STORES.find(s => s.storeId === id);
}
